### PR TITLE
3378/Optimize userlist in dashboard

### LINKED ISSUE #3378: Failed authentication in dashboard
The userlist in the dashboard could be optimized.

* We could only list one failed user once.
   * sort them by latest error
   * sort them by the number of fails of this user
* add the fails in brackets behind the username

### PR DESCRIPTION
**Pull request by Sebastian-Lemling**
The userlist in the dashboard could be optimized.

- [x] list one failed user once.

- [x] sort them by the number of fails of this user

- [x] sort them by latest error

- [x] add the fails in brackets behind the username

closes #3378

### CODE REVIEW

File: privacyidea/static/components/dashboard/controllers/dashboardControllers.js [hunk 1]
```diff
@@ -111,26 +111,49 @@ myApp.controller("dashboardController", ["ConfigFactory", "TokenFactory",
...
+          $scope.authentications.users.sort(function(a, b) {
+            if (a.fails == b.fails) {
+                return b.latestError - a.latestError;
+            }
+            return b.fails - a.fails;
+          });
+          // Add the number of fails in brackets after the username
+          $scope.authentications.users = $scope.authentications.users.map(function(user) {
+              user.realm += " [" + user.fails + "]";
+              return user;
```
Comment (cornelinux) [inline privacyidea/static/components/dashboard/controllers/dashboardControllers.js:153]: I find this irritating to add the number of fails to the user.realm.
PLease check the following:

Remove lines 150..153!

You sill have the `fails` in `authentication.users`.

File: privacyidea/static/components/dashboard/views/dashboard.html [hunk 2]
```diff
@@ -60,12 +60,16 @@
                                 <td translate>failed users / tokens</td>
                                 <td>
                                     <span ng-repeat="userobj in authentications.users">
-					    {{ ! $first ? "| " : "" }}<a ui-sref="user.details({username: userobj.user, realmname: userobj.realm})">
-                                        {{ userobj.user }}@{{ userobj.realm }}</a>
+                                        {{ !$first ? "| " : "" }}
+                                        <a ui-sref="user.details({
+                                        username: userobj.user,
+                                        realmname: userobj.realm.split(' ')[0]})">
```
Comment (cornelinux) [inline privacyidea/static/components/dashboard/views/dashboard.html:66]: since in this case now `userobj` has the elements "user", "realm" and "fails" you can remove the `split`ing.

File: privacyidea/static/components/dashboard/views/dashboard.html [hunk 3]
```diff
@@ -60,12 +60,16 @@
...
+                                            {{ userobj.user }}@{{ userobj.realm }}
+                                        </a>
```
Comment (cornelinux) [inline privacyidea/static/components/dashboard/views/dashboard.html:68]: Add here the fails:

~~~~html
 [{{ userobj.fails }}]
~~~~

This will have the same result without misusing the userobj.realm.
~~~~

**Review by cornelinux — CHANGES_REQUESTED** [review]

File: privacyidea/static/components/dashboard/controllers/dashboardControllers.js (hunk 1 above)
Comment (NNLemling) [reply privacyidea/static/components/dashboard/controllers/dashboardControllers.js]: fixed in 2746443f2b3f30f95acb50ab841e51133ace6e9c.

File: privacyidea/static/components/dashboard/views/dashboard.html (hunk 2 above)
Comment (NNLemling) [reply privacyidea/static/components/dashboard/views/dashboard.html]: fixed in 2746443f2b3f30f95acb50ab841e51133ace6e9c.

File: privacyidea/static/components/dashboard/views/dashboard.html (hunk 3 above)
Comment (NNLemling) [reply privacyidea/static/components/dashboard/views/dashboard.html:68]: fixed in 2746443f2b3f30f95acb50ab841e51133ace6e9c.

**Review by cornelinux — COMMENTED** [review]
Looks good to me.
Please check my comments and consider if you want to change some things accordingly. Thanks.

File: privacyidea/static/components/dashboard/controllers/dashboardControllers.js [hunk 4]
```diff
@@ -111,26 +111,44 @@ myApp.controller("dashboardController", ["ConfigFactory", "TokenFactory",
...
+          angular.forEach(data.result.value.auditdata, function(auditentry){
+              if (auditentry.user) {
+                  // Check if the user already exists in the dictionary
+                  if (!$scope.authentications.users[auditentry.user + "-" + auditentry.realm]) {
+                      // Add the user to the dictionary with a count of 1 and the latest error date
+                      $scope.authentications.users[auditentry.user + "-" + auditentry.realm] = {"user": auditentry.user, "realm": auditentry.realm, "fails": 1, "latestError": auditentry.date};
+                  } else {
+                      // Increment the number of fails for the existing user and update the latest error date
+                      $scope.authentications.users[auditentry.user + "-" + auditentry.realm].fails++;
+                      if (auditentry.date > $scope.authentications.users[auditentry.user + "-" + auditentry.realm].latestError) {
```
[the remark this answers is not in the document]
Comment (NNLemling) [reply privacyidea/static/components/dashboard/controllers/dashboardControllers.js:134]: I think it's a date. So the ">" comparison should work as expected.

File: privacyidea/static/components/dashboard/controllers/dashboardControllers.js [hunk 5]
```diff
@@ -111,26 +111,44 @@ myApp.controller("dashboardController", ["ConfigFactory", "TokenFactory",
...
+                          $scope.authentications.users[auditentry.user + "-" + auditentry.realm].latestError = auditentry.date;
+                      }
+                  }
+              } else {
+                  $scope.authentications.serials.push(auditentry.serial);
+              }
+          });
+          // Convert the dictionary to an array and sort it by the number of fails and the latest error date
+          $scope.authentications.users = Object.values($scope.authentications.users);
+          $scope.authentications.users.sort(function(a, b) {
```
[the remark this answers is not in the document]
Comment (NNLemling) [reply privacyidea/static/components/dashboard/controllers/dashboardControllers.js:144]: fixed in 5a61e70631c34fe625b134ea7013f41fa4b7558c.

**Review by cornelinux — APPROVED** [review]
